### ISSUE TITLE
Deploy app as static site to Netlify

### ISSUE THREAD

**Issue by sippsack** [rolandkrueger/git-whiteboard-app#16]
maybe as git.canv.as?

**Comment by sippsack** [comment]
Ein erstes Deployment hat funktioniert, er baut aber erstmal nur den develop Branch des Forks https://github.com/sippsack/git-whiteboard-app und hinkt damit in der Aktualität immer etwas hinterher.

Aufrufbar unter: https://git-whiteboard-app.netlify.app/

Aufruf in Netlify Deployment: chmod a+x ./gradlew && ./gradlew clean build

Deployed wird dann alles was im Verzeichnis build/distributions liegt
* da würde aber die index.html und die *.js (ggf. die *.js.map) reichen
* aktuell liegen da auch ein jar und ein zip File mit mehreren MB
* ggf. muesste man die notwendigen Daten noch mit "cp .. build/dist" kopieren und dann build/dist bei Netlifiy deployen

TODOs:
* Netlify-Account mit Haupt-Repo verbinden, ggf. Repo in eine Organisation verschieben (dann könnten mehrere gleichberechtigt Owner/Maintainer sein)
* Deployment-Prozess noch verbessern (unnötige Dateien beim Deployment weglassen)
* Umstieg auf Master-Branch und regelmässig die develop-Stände nach Master mergen

**Comment by sippsack** [comment]
TODOs:
* Git-Revision in Git-Whiteboard-App anzeigen, um zu sehen, welcher Stand/Version deployed ist

**Comment by rolandkrueger** [comment]
> TODOs:
> 
> * Git-Revision in Git-Whiteboard-App anzeigen, um zu sehen, welcher Stand/Version deployed ist

This works now starting with version 1.0: the current version is shown in the user manual which is generated by asciidoctor.

**Comment by rolandkrueger** [comment]
I have now configured a Netlify-Deployment for the master-branch. The app is available at https://git-whiteboard.netlify.app/
